# Generated by Django 4.2 on 2024-11-04 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jcompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('available', models.BooleanField(default=True, verbose_name='فعال')),
                ('question', models.CharField(max_length=250, verbose_name='سوال')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن بلاگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['-created_date'],
            },
        ),
    ]
