# Generated by Django 4.2 on 2024-12-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcompany', '0002_questionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='موبایل یا ایمیل')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'خبرنامه',
                'verbose_name_plural': 'خبرنامه\u200cها',
                'ordering': ['-created_date'],
            },
        ),
    ]
