# Generated by Django 4.2 on 2024-10-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('title', models.CharField(max_length=50, verbose_name='نام دسته\u200cبندی')),
                ('title_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام انگلیسی دسته\u200cبندی')),
                ('primary_cat', models.CharField(choices=[('carpet', 'فرش دستبافت'), ('wallcarpet', 'تابلو\u200cفرش دستبافت'), ('kilim', 'فرش\u200cهای سنتی')], default='carpet', max_length=50, verbose_name='دسته اصلی')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=store.models.get_cover_path, verbose_name='تصویر کاور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DesignPatternModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('name', models.CharField(max_length=50, verbose_name='نقشه')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='نقشه به انگلیسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقشه',
                'verbose_name_plural': 'نقشه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('name', models.CharField(max_length=3, verbose_name='رج')),
                ('name_en', models.CharField(blank=True, max_length=3, null=True, verbose_name='رج به انگلیسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رج',
                'verbose_name_plural': 'رج\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TextureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('name', models.CharField(max_length=50, verbose_name='بافت')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='بافت به انگلیسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بافت',
                'verbose_name_plural': 'بافت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('name', models.CharField(max_length=100, verbose_name='نام برچسب')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام برچسب به انگلیسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('available', models.BooleanField(default=True, verbose_name='موجود در انبار')),
                ('name', models.CharField(max_length=150, verbose_name='نام مدل')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام مدل به انگلیسی')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد فرش')),
                ('price', models.CharField(blank=True, max_length=15, null=True, validators=[store.models.is_number], verbose_name='قیمت')),
                ('price_in', models.CharField(blank=True, max_length=15, null=True, validators=[store.models.is_number], verbose_name='قیمت اقساطی')),
                ('price_d', models.CharField(blank=True, max_length=15, null=True, verbose_name='قیمت به دلار')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='اندازه عرض(متر)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='اندازه طول(متر)')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات انگلیسی')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=store.models.get_cover_path, verbose_name='تصویر کاور')),
                ('on_sale', models.CharField(blank=True, max_length=15, null=True, validators=[store.models.is_number], verbose_name='قیمت باتخفیف')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categorymodel', verbose_name='دسته\u200cبندی')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.designpatternmodel', verbose_name='نقشه')),
                ('tags', models.ManyToManyField(to='store.tagsmodel', verbose_name='برچسب\u200cها')),
                ('texture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.texturemodel', verbose_name='بافت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.watemodel', verbose_name='رج')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=store.models.get_image_path, verbose_name='تصویر محصول')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.productmodel', verbose_name='نام مدل')),
            ],
            options={
                'verbose_name': 'تصاویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
    ]
