# Generated by Django 4.2 on 2024-10-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
