# Generated by Django 4.2 on 2024-12-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productmodel_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='length_p',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='اندازه طول جفت(متر)'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='width_p',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='اندازه عرض جفت(متر)'),
        ),
    ]
