# Generated by Django 4.2 on 2024-12-25 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_productmodel_length_p_productmodel_width_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='PileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('name', models.CharField(max_length=100, verbose_name='چله')),
                ('name_en', models.CharField(max_length=100, verbose_name='چله به انگلیسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'چله',
                'verbose_name_plural': 'چله\u200cها\u200c',
            },
        ),
    ]
