# Generated by Django 4.2 on 2024-12-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_pilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.pilemodel', verbose_name='چله'),
        ),
    ]
