# Generated by Django 4.2 on 2024-12-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productmodel_pile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilemodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='چله به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmodel', verbose_name='نام مدل'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store.tagsmodel', verbose_name='برچسب\u200cها'),
        ),
    ]
