# Generated by Django 4.2 on 2025-02-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_pilemodel_name_en_alter_productimagemodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='number',
            field=models.IntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
