# Generated by Django 4.2 on 2024-10-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن بلاگ')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=store.models.get_cover_path, verbose_name='تصویر کاور')),
                ('available', models.BooleanField(default=True, verbose_name='انتشار')),
                ('visit', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategorymodel', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ\u200cها',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogEnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییرات')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان به انگلیسی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن بلاگ به انگلیسی')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=store.models.get_cover_path, verbose_name='تصویر کاور')),
                ('available', models.BooleanField(default=True, verbose_name='انتشار')),
                ('visit', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategorymodel', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بلاگ انگلیسی',
                'verbose_name_plural': 'بلاگ\u200cهای انگلیسی',
                'ordering': ['-created_date'],
            },
        ),
    ]
